RAILS_ROOT = "scadsclean4/SCADS/piql/gradit/src/main/rails"

puts "************"
puts "Loader beginning\n\n\n"

load = [0,0,1,0]

words = [
["abate", "to lessen to subside "],
["abdication", "giving up control authority "],
["aberration", "straying away from what is normal "],
["abet", "help/encourage smb (in doing wrong) "],
["abeyance", "suspended action "],
["abhor", "to hate to detest "],
["abide", "be faithful to endure "],
["abjure", "promise or swear to give up "],
["abraded", "rubbed off worn away by friction "],
["abrogate", "repeal or annul by authority "],
["abscond", "to go away suddenly (to avoid arrest) "],
["abstruse", "difficult to comprehend obscure "],
["abut", "border on "],
["abysmal", "bottomless extreme "],
["acarpous", "effete no longer fertile worn out "],
["acclaimed", "welcomed with shouts and approval "],
["accolade", "praise approval "],
["accretion", "the growing of separate things into one "],
["accrue", "accumulate"],
["adamant", "kind of stone inflexible "],
["admonitory", "containing warning "],
["adorn", "add beauty decorate "],
["adulteration", "making unpure poorer in quality "],
["affable", "polite and friendly "],
["affinity", "close connection relationship "],
["aggravate", "make worse irritate "],
["agile", "active quick-moving "],
["agog", "eager/excited "],
["ail", "trouble be ill "],
["alacrity", "eager and cheerful readiness "],
["alcove", "recess/partially enclosed place "],
["ale", "fermented alcoholic beverage similar to but heavier than beer"],
["aleck", "one who considers himself smarter than others"],
["allegiance", "duty support loyalty "],
["alleviate", "make (pain) easier to bear "],
["alloy", "to debase by mixing with something inferior "],
["aloof", "reserved indifferent "],
["amalgamate", "mix combine unite societies "],
["ambidextrous", "able to use the left hand or the right equally well "],
["ambiguous", "doubtful uncertain "],
["ambivalent", "having both of two contrary meanings "],
["ambrosial", "extremely pleasing to taste "],
["ameliorate", "improve make better "],
["amortize", "end (a debt) by setting aside money "],
["anguish", "severe suffering "],
["animosity", "strong dislike "],
["antidote", "medicine used against a poison or a disease "],
["antithetical", "direct opposing "],
["apartheid", "brutal racial discrimination "],
["aplomb", "self-confidence "],
["apostate", "one who abandons long-held religious or political convictions "],
["apotheosis", "deification glorification to godliness "],
["appease", "make quiet or calm "],
["apprehensive", "grasping understanding fear unhappy feeling about future "],
["apprise", "give notice to inform "],
["approbation", "approval "],
["apropos", "appropriate to the situation apt "],
["apt", "well-suited quick-witted "],
["arabesque", "a complex ornate design "],
["arboreal", "of connected with trees "],
["ardor", "enthusiasm "],
["arduous", "steep difficult ascent laborious "],
["argot", "jargon slang "],
["arrant", "in the highest degree "],
["arrogance", "proud superior manner of behaviour "],
["articulate", "speak distinctly connect by joints "],
["ascend", "go or come up "],
["ascertain", "get to know "],
["ascetic", "practicing self-denial austere stark "],
["ascribe", "consider to be the origin of or belonging to "],
["aseptic", "surgically clean "],
["asperity", "roughness harshness ill temper irritability "],
["aspersion", "slander "],
["assail", "with attack violently "],
["assiduous", "diligent hard-working sedulous "],
["assuage", "make something (pain desire) less "],
["asterisk", "the mark * (e.g.. omitted letters) "],
["astringent", "substance that shrinks "],
["astute", "clever quick at seeing to get an advantage "],
["atonement", "repayment death of Jesus "],
["attenuate", "make thin. weaken enervate "],
["attune", "bring into harmony "],
["audacious", "daring foolishly bold impudent "],
["augury", "omen sign "],
["august", "majestic venerable "],
["auspicious", "favorable successful prosperous "],
["austere", "severely moral and strict simple and plain "],
["auxiliary", "helping supporting "],
["aver", "affirm assert prove justify "],
["aversion", "strong dislike "],
["avid", "eager greedy "],
["avow", "admit. Declare openly "],
["baleful", "harmful ominous causing evil "],
["balk", "obstacle purposely to get on the way of "],
["baneful", "causing harm or ruin pernicious destructive "],
["barrage", "artificial obstacle built across a river "],
["barren", "not good enough unable to have young ones without value "],
["bask", "in enjoy warmth and light "],
["beatify", "to bless make happy or ascribe a virtue to "],
["bedizen", "to adorn especially in a cheap showy manner "],
["belabor", "beat hard "],
["bellicose", "belligerent pugnacious warlike "],
["belligerent", "(person nation) waging war "],
["benefactor", "person who has given help "],
["benevolence", "wish or activity in doing good "],
["benign", "kind and gentle mild (climate) "],
["bequest", "arrangement to give something at death "],
["berate", "scold sharply "],
["bereft", "rob or dispossess of something (material) "],
["bewilder", "puzzle confuse "],
["bigot", "stubborn narrow-minded person "],
["bilge", "bulge the protuberance of a cask "],
["blandishment", "flattery coaxing "],
["blandness", "polite manner comforting uninteresting "],
["blatant", "noisy and rough "],
["blithe", "cheerful casual carefree "],
["bogus", "sham counterfeit not genuine "],
["boisterous", "loud noisy rough lacking restraint "],
["bolster", "give greatly needed support "],
["boorish", "crude offensive rude "],
["brash", "hasty rush cheeky saucy "],
["brass", "yellow metal (mixing copper and zinc) "],
["brazen", "made of brass "],
["breach", "opening broken place breaking "],
["brittle", "easily broken "],
["broach", "bring up announce begin to talk about "],
["brook", "to tolerate endure "],
["buoyant", "able to float light-hearted "],
["burgeon", "grow forth send out buds "],
["burnish", "to polish rub to a shine "],
["cabal", "a scheme or plot a group of plotters "],
["cadge", "to beg to get by begging "],
["cajole", "use flattery or deceit to persuade "],
["calipers", "metal supports attached to the legs measuring instrument "],
["calumny", "slander aspersion "],
["candid", "frank straight-forward "],
["cant", "insincere talk/jargon "],
["cantankerous", "bad-tempered/quarrelsome "],
["canvass", "discuss thoroughly sort of touting "],
["castigate", "to chastise correct by punishing "],
["castigation", "severe punishment "],
["catalyst", "substance that causes speeding up "],
["caustic", "biting sarcastic "],
["censure", "expression of blame or disapproval a rebuke "],
["centurion", "leader of a unit of 100 soldiers "],
["chary", "cautious wary "],
["chastened", "corrected punished "],
["chastisement", "punishment "],
["chauvinist", "a blindly devoted patriot "],
["chicanery", "legal trickery/false argument "],
["chisel", "steel tool for shaping materials "],
["churl", "bad-tempered person "],
["clamor", "shout complain with a lot of noise "],
["clientele", "customers "],
["clinch", "come to grips/settle conclusively "],
["cling", "to resist separation "],
["clot", "half-solid lump formed from liquid "],
["cloture", "closing device (in Parliament) to end a debate by voting "],
["coagulation", "change to a thick and solid state "],
["coalescing", "coming together and uniting into one substance "],
["coax", "get smb to do something by kindness "],
["coda", "passage that completes a piece of music "],
["coddle", "treat with care and tenderness "],
["coerce", "compel to force to make obedient "],
["coeval", "of the same period coexisting "],
["cogent", "strong convincing "],
["cogitate", "think deeply mediate "],
["cognizant", "being fully aware of "],
["cohort", "a group or band of people"],
["colander", "bowl-shaped vessel with many holes used to drain off water "],
["collusion", "secret agreement for a deceitful purpose "],
["combustion", "process of burning "],
["commemorate", "keep the memory of "],
["commodious", "having plenty of space for what is needed "],
["commuter", "person who travels regularly "],
["complaisance", "tending to comply obliging willingness to please "],
["compunction", "feeling of regret for one's action "],
["conceal", "hide keep secret "],
["conceit", "over-high opinion of too much pride "],
["conciliatory", "reconciling soothing comforting mollifying "],
["concord", "agreement or harmony "],
["concur", "agree in opinion happen together "],
["condense", "increase in density strength make laconic "],
["Conduce", "To bring about"],
["condone", "forgive "],
["congeal", "make or become stiff and solid "],
["conjoin", "to join together "],
["connoisseur", "a person with good judgement (e.g.. in art) "],
["connotation", "suggestion in addition to "],
["consequential", "pompous self important "],
["console", "give comfort or sympathy to "],
["conspicuous", "easily seen remarkable "],
["consternation", "surprise and fear dismay "],
["constrain", "compel "],
["constrict", "make tight or smaller "],
["consume", "get to the end of "],
["consummate", "perfect/make perfect/complete "],
["contemn", "to scorn or despise "],
["contentious", "argumentative pugnacious combative quarrelsome "],
["contiguous", "touching neighboring near "],
["contrite", "filled with deep sorrow for wrongdoing "],
["contumacious", "insubordinate rebellious "],
["conundrum", "a riddle dilemma enigma "],
["conviction", "convincing firm belief "],
["convoke", "call together summon "],
["convoluted", "complicated coiled twisted "],
["cordial", "warm and sincere "],
["cordon", "line (of police acting as a guard) "],
["cornucopia", "abundant supply "],
["corporeal", "physical of or for the body "],
["correlate", "have a mutual relation "],
["corroboration", "additional strengthening evidence "],
["countenance", "to favor or approve of "],
["counterfeit", "forgery "],
["countervail", "counterbalance "],
["covert", "disguised "],
["covetous", "eagerly desirous "],
["cower", "crouch shrink back "],
["coy", "shy/modest (esp of a girl) "],
["crass", "very great (es. stupidity) "],
["cravat", "piece of linen worn as a necktie "],
["craven", "cowardly "],
["crease", "line made by crushing white line on the ground in cricket "],
["credulity", "too great a readiness to believe things "],
["credulous", "ready to believe things "],
["crush", "press lose shape subdue overwhelm "],
["cryptic", "secret with a hidden meaning "],
["cumbersome", "burdensome heavy and awkward to carry "],
["curmudgeon", "bad-tempered person "],
["curriculum", "course of study "],
["cursory", "quick hurried "],
["curtail", "make shorter then was planned "],
["dainty", "pretty/delicate(food)/difficult to please "],
["daunt", "intimidate make fearful "],
["dawdler", "person who is slow waste of time "],
["dearth", "shortage "],
["debacle", "a breakup overthrow sudden disaster "],
["decorum", "propriety properness "],
["decree", "order given by authority "],
["decry", "disapprove of "],
["defer", "postpone give way (to show respect) "],
["deferential", "showing respect "],
["defiance", "open disobedience or resistance "],
["delineate", "to portray depict sketch out "],
["deluge", "great flood heavy rush of water "],
["demagogue", "person appealing not to reasons "],
["demur", "to hesitate raise objections "],
["denigrate", "blacken belittle sully defame "],
["denouement", "an outcome or solution the unraveling of a plot "],
["deplete", "use until none remains "],
["deposition", "dethronement depositing "],
["deprave", "make morally bad corrupt "],
["deprecate", "protest against express disapproval of "],
["dereliction", "deserting and leaving to fall into ruins "],
["derision", "ridicule mockery deriding "],
["derivative", "unoriginal obtained from another source "],
["derogatory", "insulting tending to damage "],
["descry", "catch sight of see something in the distance "],
["desiccant", "substance used to absorb moisture "],
["desuetude", "cessation of use disuse "],
["desultory", "aimless haphazard digressing at random "],
["deter", "discourage hinder "],
["detraction", "slandering verbal attack aspersion "],
["detumescence", "diminishing or lessening of swelling "],
["deviance", "being different in moral standards (from normal) "],
["dexterity", "skill (esp. in handling) "],
["diaphanous", "transparent gauzy "],
["diatribe", "bitter and violent attack in words "],
["didactic", "intended to instruct"],
["diffidence", "shyness "],
["dilate", "speak comprehensively become wider large "],
["disallow", "refuse to allow or accept as a correct "],
["discern", "see with an effort but clearly "],
["discomfit", "confuse embarrass "],
["disconcert", "upset the self-possession of "],
["discountenance", "refuse to approve of "],
["discourse", "speech lecture "],
["discredit", "refuse to believe "],
["discreet", "careful/prudent "],
["discrete", "individually distinct "],
["disdain", "look on with contempt "],
["disencumber", "free from encumbrance "],
["disheveled", "untidy "],
["disingenuous", "sophisticated artful trying to deceive cunning "],
["disinter", "dig up from the earth "],
["dislodge", "move force from the place occupied "],
["dismal", "sad gloomy miserable "],
["disparate", "essentially different "],
["disproof", "proof to the contrary "],
["dissemble", "speak or behave so as to hide something (in mind) "],
["disseminate", "distribute (esp. ideas) "],
["dissent", "have a different opinion refuse to assent "],
["dissolution", "disintegration looseness in morals "],
["distraught", "distracted violently upset in mind "],
["divergence", "getting farther apart from a point "],
["divestiture", "taking off getting rid of giving up "],
["divulge", "make known something secret "],
["doggerel", "trivial poorly constructed verse "],
["dogmatic", "positive certain arbitrary without room for discussion "],
["dolt", "stupid fellow "],
["dormant", "in a state of inactivity but awaiting development "],
["dote", "show much fondness center one's attention "],
["drawl", "slow way of speaking "],
["droll", "jesting "],
["drone", "male bee person who isn't self-employed "],
["drowsiness", "feeling sleepy half asleep "],
["dubious", "feeling doubt "],
["dud", "no use person something that fails "],
["dulcet", "melodious harmonious "],
["dupe", "cheat make a fool of "],
["duplicity", "deliberate deception "],
["duress", "threats to compel smb "],
["dwarf", "person or smb much below the usual size "],
["dynamo", "a generator something that produces electric current "],
["earthenware", "dishes made of baked clay "],
["ebullience", "exuberance outburst of feeling "],
["ebullient", "overflowing with enthusiasm showing excitement "],
["ecumenical", "representing the whole Christian world "],
["edacious", "voracious devouring "],
["eddy", "circular or spiral movement (e.g.. of wind) "],
["edible", "fit to be eaten/not poisonous "],
["effete", "infertile worn out weak "],
["efficacy", "production of a desired result "],
["effluvia", "outflow in a stream of particles a noxious odor or vapor "],
["effrontery", "boldness impudence arrogance "],
["egress", "way out exit "],
["elaborate", "worked out with much care in great detail "],
["elegy", "a lament a melancholy composition "],
["elicit", "draw out "],
["eloquence", "fluent speaking skillful use of language "],
["emaciate", "make thin and weak "],
["embellish", "make beautiful "],
["embezzle", "use in a wrong way for one's own benefit "],
["emote", "stir up excite "],
["empirical", "relying on experiment "],
["encapsulate", "enclose in capsule "],
["encomium", "warm or glowing praise eulogy panegyric "],
["encumbrance", "burden things that get on the way of "],
["endearing", "making dear or liked "],
["endemic", "epidemic "],
["epiphany", "a sudden realization"],
["endorse", "write one's name on the back of "],
["enduring", "lasting "],
["enervate", "weaken deprive of strength attenuate "],
["engender", "cause produce give rise to "],
["engrave", "impress deeply "],
["engrossing", "taken up all the time or attention writing in large or formal"],
["engulf", "swallow up "],
["enigma", "something that is puzzling "],
["enmity", "hatred being an enemy "],
["ensign", "flag/badge "],
["entangle", "put into difficulties "],
["enthral", "please greatly/enslave (fig) "],
["entice", "tempt or persuade "],
["entreat", "ask earnestly "],
["enunciate", "pronounce (words)/express a theory "],
["enzyme", "catalyst "],
["epicurean", "devoted to pleasure (sensuous enjoyment) "],
["epistle", "letter "],
["epithet", "adjective "],
["epitome", "brief summary representative example a typical model "],
["equable", "steady regular "],
["equanimity", "calmness of temperament "],
["equilibrium", "state of being balanced "],
["equipoise", "equal distribution of weight equilibrium "],
["equivocal", "having a double or doubtful meaning suspicious "],
["equivocate", "try to deceive by equivocal language "],
["eradicate", "get rid of pull up by the roots "],
["erratic", "irregular in behaviour or opinion "],
["erudite", "learned scholarly "],
["eschew", "avoid "],
["esoteric", "abstruse intended only for a small circle of "],
["espouse", "marry give one's support to "],
["eulogy", "formal praise panegyric "],
["euphoria", "elation state of pleasant excitement "],
["euthanasia", "easy and painless death "],
["evasive", "tending to evade "],
["evince", "to show clearly to indicate "],
["evoke", "call up bring out "],
["excoriation", "severe criticism "],
["exculpate", "to clear from a charge of guilt "],
["exhaustive", "complete thorough "],
["exigency", "emergency an urgent situation "],
["exoneration", "set smb clear free (e.g.. from blame) "],
["exorbitant", "much too high or great "],
["expatiate", "to roam wander freely "],
["expedient", "likely to be useful for a purpose "],
["expiation", "ending expiring "],
["exploit", "brilliant achievement develop use selfishly "],
["expostulate", "argue earnestly to dissuade correct or protest "],
["expurgate", "to remove obscenity purify censor "],
["exscind", "to cut out cut away "],
["extant", "still in existence "],
["extempore", "without previous thought or preparation "],
["extenuate", "reduce the strength of lessen seriousness partially excuse "],
["extinct", "no longer active "],
["extinguish", "end the existence of/wipe or put out "],
["extirpate", "to destroy exterminate cut out exscind "],
["extol", "praise highly "],
["extort", "obtain by threats violence "],
["extralegal", "outside the law "],
["extricable", "that can be freed "],
["extrovert", "cheerful person "],
["exuberance", "state of growing vigorously being full of life "],
["facetious", "humorous funny jocular "],
["facile", "easily done "],
["fagged", "too tired, exhausted"],
["fallacious", "based on error "],
["falter", "waver/move in an uncertain manner "],
["fatuous", "without sense foolish self-satisfaction "],
["fawn", "young deer try to win smb's favor "],
["feckless", "lacking purpose or vitality ineffective careless "],
["fecund", "fertile "],
["feint", "pretend "],
["felicitous", "apt suitably expressed well chosen apropos "],
["felon", "person guilty of murder "],
["ferment", "substance become excited "],
["ferocity", "savage cruelty "],
["ferret", "discover by searching search "],
["fervid", "showing earnest feeling "],
["fervor", "warmth of feelings earnestness "],
["fetid", "stinking "],
["fetter", "to shackle put in chains "],
["feud", "bitter quarrel over a long period of time "],
["fidelity", "loyalty accuracy "],
["fidget", "move restlessly make nervous "],
["figurehead", "carved image on the prow of a ship "],
["finesse", "delicate way of dealing with a situation "],
["finical", "too fussy about food clothing etc. "],
["finicky", "finical "],
["fission", "splitting or division (esp. of cells) "],
["fixate", "stare at "],
["flak", "criticism/anti-aircraft guns "],
["flamboyant", "brightly colored florid "],
["flaunting", "show off complacently "],
["flax", "pale yellow (hair) a plant "],
["fledged", "able to fly trained experienced "],
["fleet", "number of ships quick-moving "],
["flinch", "draw move back wince "],
["flop", "fail/move/fall clumsily "],
["florid", "very much ornamented naturally red (e.g.. of face) "],
["flout", "reject mock to go against (as in going against tradition) "],
["fluke", "lucky stroke "],
["fluster", "make nervous or confused "],
["foible", "defect of character (a person is wrongly proud) "],
["foil", "prevent from carrying out contrast "],
["foment", "put something warm (to lessen the pain) "],
["foolproof", "incapable of failure or error "],
["foppish", "like a man who pays too much attention to his clothes "],
["forage", "food for horses and cattle "],
["forbear", "refrain from be patient ancestor "],
["forbearance", "patience willingness to wait "],
["ford", "shallow place in a river (to cross) "],
["forestall", "prevent by taking action in advance preempt "],
["forfeit", "suffer the loss of something"],
["forge", "workshop for the shaping of metal to shape metal lead "],
["forgery", "counterfeit "],
["forswear", "renounce disallow repudiate "],
["foster", "nurture care for "],
["fracas", "noisy quarrel "],
["fragile", "easily injured broken or destroyed "],
["fragrant", "sweet-smelling "],
["frantic", "wildly excited with joy pain anxiety "],
["frenetic", "frantic frenzied "],
["fret", "worry irritation wear away "],
["fringe", "edge ornamental border part of hair over the forehead "],
["froward", "intractable not willing to yield or comply stubborn "],
["frugal", "careful economical "],
["fulmination", "bitter protest "],
["fulsome", "disgusting offensive due to excessiveness "],
["gainsay", "to deny to oppose"],
["garble", "make unfair selection from facts "],
["garner", "to gather and save to store up "],
["garrulity", "talkativeness "],
["garrulous", "too talkative "],
["gaucherie", "socially awkward tactless behavior "],
["germane", "relevant pertinent to "],
["gist", "the point general sense "],
["glean", "gather facts in small quantities "],
["glib", "ready and smooth but not sincere "],
["glimmer", "weak/unsteady light "],
["gloat", "over look at with selfish delight "],
["glut", "supply to much fill to excess "],
["gnaw", "waste away bite steadily "],
["goad", "something urging a person to action "],
["gorge", "eat greedily/narrow opening with a stream "],
["gossamer", "soft light delicate material "],
["gouge", "tool for cutting grooves in wood "],
["gourmand", "a person who is devoted to eating and drinking to excess"],
["grandiloquent", "using pompous words "],
["grave", "serious requiring consideration "],
["graze", "touch or scrape lightly in passing "],
["gregarious", "living in societies liking the company "],
["grievous", "causing grief or pain serious dire grave "],
["grovel", "crawl humble oneself "],
["guile", "deceit cunning "],
["gullible", "easily gulled "],
["gush", "burst out suddenly/talk ardently "],
["gust", "outburst of feeling sudden rain wind fire etc. "],
["hack", "cut roughly hired horse "],
["halcyon", "calm and peaceful "],
["hallow", "to make holy consecrate "],
["harangue", "a long passionate speech "],
["harbinger", "something or smb that foretells the coming of "],
["harrow", "to distress create stress or torment "],
["haughty", "arrogant conceited "],
["heed", "attention/give notice to "],
["heinous", "odious (of crime) "],
["heresy", "belief contrary to what is generally accepted "],
["hermetic", "sealed by fusion "],
["heterogeneous", "made up of different kinds "],
["hew", "make by hard work cut (by striking) "],
["highbrow", "(person) with superior tastes "],
["hirsute", "hairy shaggy "],
["hoax", "mischievous trick played on smb for a joke "],
["hoi", "polloi the masses the rabble "],
["hollow", "not soled with hole "],
["holster", "leather case for a pistol "],
["homiletics", "act of preaching "],
["hone", "stone used for sharpening tools "],
["hoodwink", "trick mislead "],
["hospitable", "liking to give hospitality "],
["hubris", "arrogant pride "],
["hush", "make or become silent "],
["husk", "worthless outside part of anything "],
["hypocrisy", "falsely making oneself appear to be good "],
["iconoclast", "person who attacks popular beliefs "],
["idiosyncrasy", "personal mannerism "],
["idolatry", "excessive admiration of "],
["idyll", "a carefree episode or experience "],
["ignoble", "dishonorable common undignified "],
["ignominious", "shameful dishonorable undignified disgraceful "],
["illicit", "unlawful forbidden "],
["imbroglio", "complicated and embarrassing situation "],
["immaculate", "pure faultless "],
["imminent", "likely to come or happen soon "],
["immutable", "that cannot be changed "],
["impair", "worsen diminish in value "],
["impassive", "unmoved feeling no sign of passion "],
["impecunious", "having little or no money "],
["impede", "hinder get in the way of "],
["impediment", "something that hinders (e.g. stammer) "],
["impending", "imminent being about to happen expected "],
["imperative", "urgent essential "],
["imperious", "commanding haughty arrogant "],
["impermeable", "that cannot be permeated "],
["imperturbable", "calm not capable of being excited "],
["impervious", "not allowing to pass through (of materials) "],
["imperviousness", "haughty arrogant commanding "],
["impetuous", "having sudden energy impulsive thrusting ahead forceful "],
["impiety", "lack of reverence or dutifulness "],
["implacable", "incapable of being placated unpleasable "],
["implicate", "show that smb has a share "],
["implicit", "implied though not plainly expressed"],
["implosion", "collapse bursting inward "],
["importune", "beg urgently solicit (of a prostitute) "],
["imprecation", "an invocation of evil a curse "],
["impromptu", "without preparation "],
["impudent", "rash indiscreet "],
["impugned", "challenged to be doubted "],
["impute", "to attribute to a cause or source ascribe "],
["inadvertent", "not paying proper attention "],
["inane", "silly senseless "],
["inasmuch", "since because "],
["incense", "make angry "],
["incessant", "often repeated continual "],
["inchoate", "not yet fully formed rudimentary elementary "],
["incipient", "beginning "],
["incise", "engrave make a cut in "],
["incite", "stir up rouse "],
["inclined", "directing the mind in a certain direction "],
["incongruous", "out of place not in harmony or agreement "],
["incorrigibility", "cannot be cured or corrected "],
["incredulous", "skeptical unwilling to believe "],
["inculcate", "fix firmly by repetition "],
["incumbents", "official duties "],
["incursion", "a raid a sudden attack "],
["indefatigability", "not easily exhaustible tirelessness "],
["indelible", "that cannot be rubbed out "],
["indigence", "poverty "],
["indigenous", "native "],
["indistinct", "not easily heard seen clearly marked "],
["indolence", "laziness "],
["indomitable", "not easily discouraged or subdued "],
["indulge", "gratify give way to satisfy allow oneself "],
["indulgent", "inclined to indulge "],
["ineffable", "to great to be described in words "],
["ineluctable", "certain inevitable "],
["inept", "unskillful said or done at the wrong time "],
["ineptitude", "quality of being unskillful "],
["inferno", "hell "],
["infuriate", "fill with fury or rage "],
["infuse", "put pour fill "],
["ingenuous", "naive young artless frank honest sincere "],
["ingest", "take in by swallowing "],
["inimical", "harmful or friendly "],
["inimitable", "defying imitation unmatchable "],
["innocuous", "causing no harm "],
["inscrutable", "incapable of being discovered or understood "],
["insensible", "unconscious unresponsive unaffected "],
["insinuate", "suggest unpleasantly make a way for something gently "],
["insipid", "without taste or flavor "],
["insouciant", "unconcerned carefree "],
["insularity", "narrow-mindedness isolated "],
["insurrection", "rising of people to open resistance to "],
["interdict", "prohibit forbid "],
["interim", "as an installment "],
["intersperse", "place here and there "],
["intransigence", "unwillingness to compromise stubbornness intractability "],
["intransigent", "uncompromising "],
["intrepid", "fearless brave undaunted "],
["introspection", "examining one's own thoughts and feelings "],
["inundate", "flood cover by overflowing "],
["inured", "accustomed to adapted "],
["invective", "abusive language curses "],
["inveigh", "to attack verbally denounce deprecate "],
["inveterate", "deep-rooted. long-established "],
["invincible", "too strong to be defeated "],
["involute", "complex "],
["irascible", "irritable easily angered "],
["irate", "angry "],
["ire", "anger "],
["irksome", "tiresome "],
["irresolute", "hesitating undecided "],
["irrevocable", "final and unalterable "],
["itinerate", "to travel from place to place to peregrinate "],
["jabber", "talk excitedly utter rapidly "],
["jagged", "notched, rough"],
["jibe", "gibe make fun of "],
["jocular", "meant as a joke "],
["judicious", "sound in judgment wise "],
["knit", "draw together unite firmly "],
["labyrinthine", "to entangle the state of affairs "],
["lachrymose", "causing tears tearful "],
["lackluster", "(of eyes) dull "],
["lament", "show feel great sorrow "],
["lassitude", "weariness tiredness "],
["latent", "present but not yet active developed or visible "],
["laudatory", "expressing or giving praise "],
["lavish", "giving or producing freely liberally or generously "],
["legacy", "something handed down from ancestors "],
["levee", "formal reception/embankment "],
["levity", "lack of seriousness "],
["libel", "statement that damages reputation "],
["liberality", "free giving generosity "],
["libertine", "immoral person "],
["lien", "legal claim until a debt on it is repaid "],
["limn", "paint portray "],
["limp", "lacking strength walking unevenly "],
["lionize", "treat as a famous person "],
["lithe", "bending twisting "],
["loll", "rest to sit or stand in a lazy way hang (dog's tongue)"],
["lope", "move along with long strides "],
["loquacious", "talkative garrulous "],
["lucubrate", "write in scholarly fashion "],
["luculent", "easily understood lucid clear "],
["lugubrious", "mournful excessively sad "],
["lull", "become quiet or less active "],
["lumber", "move in a clumsy/noisy way "],
["luminary", "star light-giving body "],
["lurk", "be out of view ready to attack "],
["lustrous", "being bright polished "],
["macabre", "gruesome suggesting death "],
["macerate", "make or become soft by soaking in water "],
["machination", "plot scheme (esp. evil) "],
["maladroit", "tactless clumsy "],
["malapropism", "misuse of a word (for one that resembles it) "],
["malevolence", "wishing to do evil "],
["malign", "injurious speak ill of smb tell lie "],
["malinger", "to fake illness or injury in order to shirk a duty "],
["malleable", "yielding easily shaped moldable adapting "],
["manacle", "chains for the hands or feet "],
["massacre", "cruel killing of a large number of people "],
["matriculation", "be admitted enter a university as a student "],
["maudlin", "sentimental in a silly or tearful way "],
["maul", "hurt by rough handling "],
["maverick", "rebel nonconformist "],
["mellifluous", "sweetly flowing "],
["mendacity", "dishonesty "],
["mendicant", "a beggar "],
["mercurial", "quick changeable in character fleeting "],
["meretricious", "attractive on the surface but of little value "],
["mesmerize", "hypnotize "],
["meticulous", "giving great attention to details "],
["mettle", "quality of endurance or courage "],
["mettlesome", "courageous high-spirited "],
["middling", "fairly good but not very good "],
["minatory", "menacing threatening "],
["mince", "pronounce or speak affectedly euphemize "],
["misanthrope", "person who hates mankind "],
["mischievous", "harmful causing mischief "],
["miser", "person who loves wealth and spends little "],
["misogynist", "one who hates women/females "],
["mite", "Avery small amount, portion, or particle"],
["moderation", "quality of being limited not extreme "],
["mollify", "make calmer or quieter "],
["molt", "moult lose hair feathers before new growing "],
["morbid", "diseased unhealthy (e.g.. about ideas) "],
["morose", "ill-tempered unsocial "],
["muffler", "cloth worn round the neck/silencer "],
["multifarious", "varied motley greatly diversified "],
["mundane", "worldly as opposed to spiritual commonplace everyday "],
["myriad", "very great number "],
["nadir", "lowest weakest point "],
["nascent", "coming into existence emerging "],
["nebulous", "cloud-like hazy vague indistinct "],
["negligent", "taking too little care "],
["neophyte", "person who has been converted to a belief "],
["nexus", "a connection tie or link "],
["nibble", "show some inclination to accept (an offer) "],
["noisome", "offensive disgusting (smell) "],
["nonchalant", "not having interest "],
["nonplused", "greatly surprised "],
["nostrum", "a quack remedy an untested cure "],
["noxious", "harmful "],
["nugatory", "trifling/worthless "],
["obdurate", "hardened and unrepenting stubborn inflexible "],
["obfuscate", "to darken make obscure muddle "],
["oblivious", "unaware having no memory "],
["obloquy", "abusively detractive language sharp criticism vituperation "],
["obsequious", "too eager to obey or serve "],
["obstreperous", "noisy loud "],
["obtain", "to be established accepted or customary "],
["obtrusive", "projecting prominent undesirably noticeable "],
["obtuse", "blunt/stupid "],
["obviate", "to make unnecessary get rid of "],
["occluded", "blocked up "],
["odious", "repulsive hateful "],
["odium", "contempt dislike aversion "],
["odor", "smell favor reputation "],
["officious", "too eager or ready to help offer advice "],
["ominous", "threatening "],
["onerous", "needing effort burdensome "],
["opaqueness", "dullness/not allowing light to pass through "],
["opprobrious", "showing scorn or reproach "],
["ossify", "to turn to bone to settle rigidly into an idea "],
["ostensible", "seeming appearing as such professed "],
["ostentation", "display to obtain admiration or envy "],
["ostracism", "shut out from society refuse to meet talk "],
["overhaul", "examine thoroughly to learn about the condition "],
["overweening", "presumptuously arrogant overbearing immoderate being a jerk "],
["paean", "song of praise or triumph "],
["palate", "roof of the mouth sense of taste "],
["palatial", "magnificent "],
["palliate", "lessen the severity of "],
["palpability", "can be felt touched understood "],
["palpitate", "tremble beat rapidly and irregularly "],
["panegyric", "formal praise eulogy "],
["paradigm", "a model example or pattern "],
["parenthesis", "sentence within another one something separated "],
["pariah", "an outcast a rejected and despised person "],
["parley", "negotiation, discussion between enemies"],
["parsimonious", "too economical miserly "],
["partisan", "one-sided committed to a party biased or prejudiced "],
["patron", "regular customer person who gives support "],
["paucity", "scarcity a lacking of "],
["peccadillo", "small sin small weakness in one's character "],
["pedantic", "bookish showing off learning "],
["pedestrian", "commonplace trite unremarkable "],
["pellucid", "transparent easy to understand "],
["penchant", "strong inclination a liking "],
["penitent", "feeling or showing regret "],
["penurious", "poor/stingy "],
["penury", "extreme poverty "],
["peregrination", "traveling about wandering "],
["peremptory", "urgent imperative unchallengeable ending debate "],
["perfidious", "treacherous faithless "],
["perfidy", "treachery breaking of faith "],
["perfunctory", "done as a duty without care "],
["perilous", "dangerous "],
["peripatetic", "wandering "],
["perish", "be destroyed decay "],
["perjury", "willful FALSE statement unlawful act "],
["permeate", "spread into every part of "],
["pernicious", "harmful injurious "],
["perpetrate", "be guilty commit (a crime) "],
["personable", "pleasing in appearance attractive "],
["perspicacity", "quick judging and understanding "],
["pertain", "belong as a part have reference "],
["pest", "destructive thing or a person who is nuisance "],
["petrified", "taken away power (to think feel act) "],
["petrify", "to make hard rocklike "],
["petrous", "like a rock hard stony "],
["petulant", "unreasonably impatient "],
["philistine", "a smug ignorant person one who lacks knowledge "],
["phlegmatic", "calm sluggish temperament unemotional "],
["picaresque", "involving clever rogues or adventurers "],
["pied", "of mixed colors "],
["pinch", "be too tight take between the thumb and finger "],
["pine", "waste away through sorrow or illness "],
["pious", "dutiful to parents devoted to religion "],
["piquant", "agreeably pungent stimulating "],
["pique", "hurt the pride or self-respect stir (curiosity) "],
["pitfall", "covered hole as a trap unsuspected danger "],
["pith", "essential part force soft liquid substance "],
["pivotal", "of great importance (others depend on it) "],
["placate", "soothe pacify calm "],
["plaintive", "mournful melancholy sorrowful "],
["plaque", "flat metal on a wall as a memorial "],
["platitude", "a trite or banal statement unoriginality "],
["plea", "request "],
["plead", "address a court of law as an advocate "],
["plethora", "glut "],
["pliant", "pliable easily bent shaped or twisted "],
["plod", "continue doing something without resting "],
["pluck", "pull the feathers off pick (e.g.. flowers) "],
["plumb", "get to the root of "],
["plummet", "fall plunge steeply "],
["plunge", "move quickly suddenly and with force "],
["poignant", "deeply moving keen "],
["poncho", "large piece of cloth "],
["ponderous", "heavy bulky dull "],
["portent", "omen marvelous threatening "],
["precarious", "uncertain risky dangerous "],
["precepts", "rules establishing standards of conduct "],
["preclude", "prevent make impossible "],
["precursory", "preliminary anticipating "],
["predilection", "special liking mental preference "],
["predominate", "have more power than others "],
["preen", "tidy/show self-satisfaction "],
["premature", "doing or happening something before the right time "],
["preponderance", "greatness in number strength weight "],
["presage", "warning sign "],
["presumption", "arrogance "],
["preternatural", "not normal or usual "],
["prevalent", "common "],
["prevaricate", "to equivocate to stray from the truth "],
["prim", "neat formal "],
["pristine", "primitive unspoiled pure as in earlier times unadulterated "],
["probity", "uprightness incorruptibility principle "],
["proclivity", "inclination "],
["procrastination", "keeping on putting off "],
["prodigal", "wasteful reckless with money "],
["prodigious", "enormous wonderful "],
["profane", "worldly having contempt for God "],
["profligacy", "shameless immorality "],
["profligate", "wasteful prodigal licentious extravagant "],
["profundity", "depth "],
["profuse", "abundant/lavish "],
["proliferate", "grow reproduce by rapid multification "],
["prolix", "tiring because too long "],
["prone", "prostrate inclined to (undesirable things) "],
["propagation", "increasing the number spreading extending "],
["propinquity", "nearness in time or place affinity of nature "],
["propitiatory", "conciliatory appeasing mitigating "],
["propitious", "auspicious presenting favorable circumstances "],
["prosaic", "everyday mundane commonplace trite pedestrian "],
["proscribe", "denounce as dangerous "],
["protracted", "prolonged "],
["provident", "frugal looking to the future "],
["provisional", "of the present time only "],
["provoke", "make angry vax "],
["prudence", "careful forethought "],
["prudish", "easily shocked excessively modest "],
["prune", "dried plum silly person "],
["pry", "get something inquire too curiously "],
["pucker", "wrinkle "],
["pugnacious", "fond of in the habit of fighting "],
["puissance", "strength "],
["punctilious", "precise paying attention to trivialities "],
["pundit", "pedant authority on a subject "],
["pungency", "sharpness stinging quality "],
["purvey", "provide supply "],
["pusillanimous", "cowardly craven "],
["putrefaction", "becoming rotten "],
["pyre", "large pile of wood for burning "],
["quack", "person dishonestly claiming to something"],
["quaff", "drink deeply "],
["quail", "lose courage turn frightened "],
["qualm", "feeling of doubt temporary feeling of sickness "],
["quandary", "state of doubt or perplexity "],
["quell", "suppress subdue "],
["quibble", "try to avoid by sophistication "],
["quiescence", "state of being passive/motionless "],
["quiescent", "at rest dormant torpid "],
["quirk", "habit or action peculiar to smb or something"],
["quixotic", "generous unselfish "],
["quotidian", "banal everyday "],
["rabble", "mob crowd the lower classes of populace "],
["raconteur", "person who tells anecdotes "],
["raffish", "low vulgar base tawdry "],
["ramify", "to be divided or subdivided to branch out "],
["rancorous", "feeling bitterness spitefulness "],
["rant", "use extravagant language "],
["rapacious", "greedy (esp for money) "],
["rarefy", "to make thin to make less dense to purify or refine "],
["rave", "act with excessive enthusiasm "],
["reactionary", "opposing progress "],
["rebuff", "snub "],
["recalcitrant", "disobedient "],
["recant", "take back as being FALSE give up "],
["recast", "cast or fashion anew "],
["recidivism", "relapse into antisocial or criminal behavior "],
["reciprocity", "granting of privileges in return for similar "],
["recitals", "a number of performance of music "],
["recluse", "person who lives alone and avoids people "],
["recompense", "make payment to reward punish "],
["reconcile", "settle a quarrel restore peace "],
["recondite", "little known abstruse "],
["recreancy", "cowardice a cowardly giving up "],
["recuperate", "become strong after illness loss exhaustion "],
["redeem", "get back by payment compensate "],
["redoubtable", "formidable causing fear "],
["refine", "make or become pure cultural "],
["refractory", "stubborn unmanageable untractable "],
["refulgent", "shining brilliant "],
["regale", "to delight or entertain to feast "],
["regicide", "crime of killing a king"],
["reiterate", "say or do again several times "],
["rejuvenation", "becoming young in nature or appearance "],
["relapse", "fall back again "],
["reminiscent", "viewing the past"],
["remonstrate", "to protest object "],
["render", "deliver provide represent "],
["renovate", "restore something to better condition "],
["renowned", "celebrated famous "],
["repast", "meal "],
["repel", "refuse to accept/cause dislike "],
["repine", "at be discontented with "],
["reproach", "scold upbraid "],
["reprobate", "person hardened in sin one devoid of decency "],
["repudiate", "disown refuse to accept or pay "],
["repulsive", "causing a feeling of disgust "],
["requite", "repay give in return "],
["rescind", "repeal/annul/cancel "],
["resigned", "unresisting submissive "],
["resilience", "quality of quickly recovering the original shape "],
["resort", "to frequently visit "],
["restive", "refusing to move reluctant to be controlled "],
["resuscitation", "coming back to consciousness "],
["retard", "check hinder "],
["reticent", "reserved untalkative silent taciturn "],
["retrospective", "Looking back on past"],
["revere", "have deep respect for "],
["reverent", "feeling or showing deep respect "],
["riddle", "puzzling person or thing "],
["rift", "split crack dissension "],
["rivet", "fix take up secure metal pin "],
["roll", "call calling of names "],
["rotund", "rich and deep plump and round "],
["ruffian", "violent cruel man "],
["rumple", "make rough "],
["sagacious", "having sound judgment perceptive wise like a sage "],
["salacious", "obscene "],
["salubrious", "healthful "],
["salutary", "remedial wholesome causing improvement "],
["sanctimony", "self-righteousness hypocritical with FALSE piety "],
["sanction", "approval (by authority) penalty "],
["sanguine", "cheerful confident optimistic "],
["sanity", "health of mind soundness of judgment "],
["sash", "long strip worn round the waist "],
["satiate", "satisfy fully "],
["saturnine", "gloomy dark sullen morose "],
["savant", "person of great learning "],
["savor", "taste flavor something"],
["sawdust", "tiny bits of wood "],
["scabbard", "sheath for the blade "],
["scent", "smell (especially pleasant) "],
["scorch", "become discolored/dry up/go at high speed "],
["scribble", "write hastily "],
["scurvy", "mean contemptible "],
["secular", "material (not spiritual) living outside monasteries "],
["sedulous", "persevering "],
["seminal", "like a seed constituting a source originative "],
["sententious", "short and pithy full of maxims/proverbs "],
["sequence", "succession connected line of "],
["sere", "make hard and without feeling "],
["sermon", "reproving a person for his faults "],
["serrated", "having a toothed edge "],
["serration", "having a toothed edge "],
["servile", "like a slave lacking independence "],
["sever", "break off "],
["severance", "severing "],
["shallow", "little depth not earnest "],
["shard", "piece of broken earthenware "],
["sheath", "cover for the blade of a weapon or a tool "],
["shrewd", "astute showing sound judgement "],
["shrill", "sharp piercing "],
["shun", "keep away from avoid "],
["shunt", "send from one track to another lay aside evade discussion "],
["sidestep", "step to one side "],
["simper", "(give a) silly/self-conscious smile "],
["sinuous", "winding undulating serpentine "],
["skiff", "small boat "],
["skit", "short piece of humorous writing "],
["slack", "sluggish dull not tight "],
["slake", "to assuage to satisfy allay "],
["slate", "king of blue-grey stone propose criticize "],
["sluggard", "lazy slow-moving person "],
["slur", "join sounds/words (indistinct) "],
["smolder", "burn slowly without flame "],
["snare", "trap "],
["snub", "treat with contempt "],
["soar", "rise fly high "],
["sober", "self-controlled "],
["sobriety", "quality or condition of being sober "],
["sodden", "soaked saturated "],
["soggy", "heavy with water "],
["solvent", "of the power of forming a solution "],
["somatic", "of the body "],
["soot", "black powder in smoke "],
["sophisticated", "complex subtle refined "],
["sophistry", "fallacious reasoning faulty logic "],
["sophomoric", "self-assured though immature affected bombastic overblown "],
["soporific", "producing sleep "],
["sordid", "wretched comfortless contemptible "],
["spear", "weapon with a metal point on a long shaft "],
["specious", "illogical of questionable truth or merit "],
["splenetic", "bad-tempered irritable "],
["splice", "join (two ends) "],
["sponge", "porous rubber for washing live at once expense "],
["spurious", "FALSE counterfeit "],
["spurn", "have nothing to do reject or refuse "],
["squalid", "foul filthy "],
["squander", "spend wastefully "],
["squat", "crouch/settle without permission "],
["stanch", "to stop the flow of a fluid "],
["steeply", "rising or falling sharply "],
["stentorian", "extremely loud and powerful "],
["stickler", "person who insists on importance of something"],
["stigma", "mark of shame or disgrace "],
["stigmatize", "describe smb scornfully "],
["sting", "something sharp "],
["stingy", "spending using unwillingly "],
["stint", "to be thrifty to set limits "],
["stipple", "paint with dots "],
["stipulate", "state or put forward as a necessary condition "],
["stolid", "showing no emotion impassive "],
["stray", "wander lose one's way "],
["streak", "long thin move very fast "],
["striated", "striped grooved or banded "],
["stride", "walk with long steps "],
["strut", "a supporting bar "],
["stygian", "hence dark gloomy "],
["stymie", "to hinder obstruct or block "],
["subdue", "overcome bring under control "],
["sublime", "extreme astounding "],
["submerge", "put under water liquid sink out of sight "],
["suborn", "induce by bribery or something to commit perjury "],
["subpoena", "written order requiring a person to appear in a low court "],
["substantiation", "giving facts to support (statement) "],
["subsume", "include under a rule "],
["succor", "assistance relief in time of distress "],
["suffice", "be enough "],
["suffocate", "cause or have difficulty in breathing "],
["sullied", "to be stained or discredited "],
["summarily", "briefly without delay "],
["sumptuous", "magnificent "],
["sundry", "various miscellaneous separate "],
["supercilious", "disdainful characterized by haughty scorn "],
["superfluous", "more then is needed or wanted "],
["superimpose", "put something on the top "],
["supersede", "take the place of "],
["supine", "lying on the back slow to act passive "],
["suppliant", "asking humbly beseeching "],
["supplicate", "make a humble petition to "],
["suppress", "prevent from being known put an end to "],
["surcharge", "additional load/charge "],
["surfeit", "satiate feed to fulness or to excess "],
["susceptibility", "sensitiveness "],
["swerve", "change direction suddenly "],
["sycophant", "person who flatter to the rich and powerful "],
["synopsis", "summary or outline "],
["taciturn", "untalkative silent "],
["tadpole", "form of a frog when it leaves the egg "],
["talon", "claw of a bird of prey "],
["tamp", "tap or drive down by repeated light blows "],
["tamper", "interfere with "],
["tangential", "suddenly changeable "],
["tarnished", "lost brightness "],
["tassel", "bunch of threads "],
["taunt", "contemptuous reproach hurtful remark "],
["taut", "tightly stretched "],
["tautology", "a repetition a redundancy "],
["tawdry", "cheap gaudy showy tacky "],
["teetotal", "oppose to alcohol "],
["telltale", "That gives warning or information"],
["temerity", "boldness brashness intrepidness "],
["temperance", "abstinence from alcohol self-control moderation "],
["temperate", "showing self-control "],
["tenacity", "firmness persistency adhesiveness tending to hang on "],
["tenuous", "insubstantial flimsy weak "],
["tepid", "lukewarm "],
["terse", "brief and to the point "],
["testiness", "witness/evidence "],
["thrift", "care economy thriving prosperous "],
["thwart", "obstruct/frustrate "],
["timid", "shy easily frightened "],
["timorous", "fearful timid afraid "],
["toady", "obsequious flatterer "],
["tonic", "something giving strength or energy "],
["topple", "be unsteady and overturn "],
["torment", "severe pain or suffering "],
["torpid", "sleeping sluggish lethargic dormant "],
["torque", "twisting force causing rotation "],
["tortuous", "devious/not straightforward "],
["tout", "person who worries others to buy something to use his service "],
["tractable", "easily controlled or guided "],
["transgress", "break go beyond (a limit) "],
["transient", "temporary fleeting "],
["transitory", "brief "],
["travesty", "parody/imitation "],
["trenchant", "forceful effective vigorous extremely perceptive incisive "],
["trepidation", "alarm excited state of mind "],
["trickle", "flow in drops "],
["trifling", "unimportant "],
["trite", "not new "],
["truce", "(agreement) stop of fighting for a time "],
["truculence", "aggressiveness ferocity "],
["trudge", "walk heavily "],
["turbid", "muddy having the sediment stirred up "],
["turbulence", "being uncontrolled violent "],
["turgid", "excessively ornate swollen or bloated "],
["turmoil", "trouble disturbance "],
["turpitude", "wickedness shamefulness "],
["turquoise", "greenish-blue precious stone "],
["tyro", "tiro beginner "],
["ubiquitous", "present everywhere "],
["ulterior", "situated beyond "],
["umbrage", "offense resentment "],
["uncouth", "rough awkward "],
["underbid", "make a lower bid then smb else "],
["undermine", "weaken gradually at the base make something under "],
["undulate", "to move in wavelike fashion fluctuate "],
["unearth", "discover and bring to light "],
["unencumbered", "easy-going trifle "],
["unfeigned", "not pretended sincere "],
["unscathed", "unharmed unhurt "],
["untoward", "unfortunate inconvenient "],
["upbraid", "scold reproach "],
["urbane", "elegant refined in manners "],
["vacillation", "being uncertain hesitating "],
["vagary", "strange act or idea "],
["vain", "without use result conceited "],
["valiant", "brave "],
["valorous", "brave "],
["vanquish", "conquer "],
["variegate", "To mark with different shade or colors"],
["veer", "change direction "],
["venal", "ready to do something dishonest "],
["veneer", "surface appearance covering the TRUE nature "],
["veneration", "regard with deep respect "],
["veracity", "truth "],
["verdant", "fresh and green "],
["verisimilitude", "appearing TRUE or real "],
["veritable", "real rightly named "],
["verve", "spirit vigor enthusiasm "],
["vestige", "trace or sign "],
["vex", "annoy distress trouble "],
["vigilance", "watchfulness self-appointed group who maintain order "],
["vigilant", "member of a vigilance committee "],
["vigorous", "strong energetic "],
["vilify", "slander say evil things "],
["vindictive", "having a desire to revenge "],
["virago", "a loud domineering woman a scold or nag "],
["visceral", "of the internal organs of the body "],
["viscous", "sticky/semi-fluid "],
["vitiate", "lower the quality weaken the strength "],
["vituperate", "curse abuse in words "],
["vivacious", "lively high-spirited "],
["volatile", "changeable inconstant fickle unstable explosive "],
["volubility", "fluency verbosity easy use of spoken language "],
["voluble", "fluent "],
["waffle", "talk vaguely and without much result "],
["waft", "scent waving movement carry lightly through "],
["wag", "merry person "],
["warmonger", "person who stirs up war "],
["warrant", "authority written order guarantee "],
["wean", "to turn away (from a habit) "],
["weigh", "measure hoe heavy something is "],
["welter", "turmoil a bewildering jumble "],
["wend", "to go proceed "],
["whimsical", "full of odd and fanciful ideas "],
["wince", "show bodily or mental pain "],
["woo", "try to win "],
["writ", "written order "],
["xenophile", "a person who is attracted to foreign peoples, cultures, or customs"],
["yarn", "tale story fibers for knitting "]
]
if (load[0] == 1)
    wordFile = File.new("words.graditdump", "w")
    wordFile.sync = true
    puts "\n\nAdding " + words.size.to_s + " words...\n"
    wordid = 1
    words.each { |w|
        puts "Adding word " + wordid.to_s + ": " + w[0] + ": " + w[1] + "...   "
        wordFile.puts(wordid.to_s + "%|%" + w[0] + "%|%" + w[1])
        wordFile.flush
        w[2] = wordid
        wordid = wordid + 1
    }
end
#wordFile.close
# wordid as integer, book name as string, linenum as integer, wordline as string

contexts = []

#puts "\n"
#puts "Starting up contexts..."

books = [ 
    ["Wuthering Heights", RAILS_ROOT + "/config/books/wuthering_heights.txt"],
    ["Heart of Darkness", RAILS_ROOT + "/config/books/heart_of_darkness.txt"],
    ["Moby Dick", RAILS_ROOT + "/config/books/moby_dick.txt"],
    ["Frankenstein", RAILS_ROOT + "/config/books/frankenstein.txt"],
    ["Midsummer Night's Dream", RAILS_ROOT + "/config/books/midsummer_nights_dream.txt"],
    ["The Odyssey", RAILS_ROOT + "/config/books/the_odyssey.txt"]
]
if (load[1] == 1)
    books.each { |b|
        puts "Reading " + b[0]
        contextcounter = 0
        bookFile = File.new(b[1], "r")
        bookText = ""
        while (line = bookFile.gets)
            print "-"
            bookText = bookText + " " + line
        end
        puts ""
        content = bookText.scan(/(\S.+?[.!?])(?=\s+|$)/)
        i = 0
        while i < content.size
            if (i % 20 == 0)
                print "."
            end
            words.each { |w|
                wordreg = /\b#{w[0]}\b/
                if wordreg.match(content[i].first.downcase)
                    text = ""
                    if i > 0
                        text << content[i-1].first
                    end
                    text << content[i].first
                    if i < (content.size-1)
                        text << content[i+1].first
                    end
                    contexts << [w[2], b[0], 0, text]
                    contextcounter = contextcounter + 1
                end
            }
            i = i+1
        end
        bookFile.close
        puts ""
        puts "Found " + contextcounter.to_s + " contexts."
        puts "Finished reading " + b[0] + "\n\n"
    }

    contextFile = File.new("contexts.graditdump", "w")

    puts "\n\nAdding " + contexts.size.to_s + " contexts...\n"
    contexts.each { |c|
        puts "Adding context for word " + c[0].to_s + ", book: " + c[1] + "...   "
        # wordid as int, book name, line number, text
        contextFile.puts(c[0].to_s + "%|%" + c[1] + "%|%" + c[2].to_s + "%|%" + c[3])
    }
    contextFile.close
end

if (load[2] == 1)

    wordlistFile = File.new("wordlists.graditdump", "w")

    puts "\n\nAdding wordlists...\n"
    (1..10).each { |n|
        wordlistFile.puts("sample" + n.to_s + "%|%" + "admin")
    }

    wordlistFile.close
    
end

if (load[3] == 1)
    
    shuffledWords = words.shuffle
    
    wordlistwordFile = File.new("wordlistwords.graditdump", "w")

    puts "\n\nAdding wordlistwords...\n"

    (1..10).each { |n|
        samples = shuffledWords[n*100..(n*100)+100]
        samples.each { |w|
            wordlistwordFile.puts("sample" + n.to_s + "%|%" + w[2].to_s)
        }
    }

    wordlistwordFile.close
end

puts "\n\n\nLoader finished"
puts "************"