#!/bin/bash

CONFIG=`dirname $0`/config
CLASSPATH='-cp `dirname $0`/scads.jar'

exec /usr/bin/java -Xmx3G -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -Djava.library.path=$MESOS_HOME/lib/java/ $CLASSPATH deploylib.mesos.JavaExecutor $CONFIG $@