#!/bin/bash

CONFIG=`dirname $0`/config
CLASSPATH='-cp `dirname $0`/scads.jar'

exec /usr/bin/java -Xmx1G -XX:MaxPermSize=512M -Djruby.thread.pooling=true -Djruby.objectspace.enabled=false -Djava.library.path=$MESOS_HOME/lib/java/ $CLASSPATH deploylib.mesos.JavaExecutor $CONFIG $@