#!/bin/bash

JARPATH=`dirname $0`

exec /usr/bin/java -Djava.library.path=$MESOS_HOME/lib/java/ -cp $JARPATH/deploy-2.1-SNAPSHOT-jar-with-dependencies.jar deploylib.mesos.JavaExecutor $JARPATH/config $@ 
